service: anon-texts-lambda-db

provider:
  name: aws
  runtime: nodejs6.10
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:*
      Resource: "*"
  environment:
      stage: ${opt:stage, self:provider.stage}

functions:
  create:
    handler: sentMessages/create.handler
    memorySize: 128
    events:
      - http:
          path: sentMessages
          method: post
          cors: true

  get:
    handler: sentMessages/get.handler
    memorySize: 128
    events:
      - http:
          path: sentMessages/{number}
          method: get
          cors: true